name: automatic release
on:
  release:
    types: [published, prereleased]
permissions:
  contents: write
jobs:
  release:
    strategy:
      matrix:
        platform:
          - os: linux
            arch: amd64
            ext:
          - os: windows
            arch: arm64
            ext: .exe
          - os: darwin
            arch: arm64
            ext:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Build
        run: go build -o default-${{ matrix.platform.os }}-${{ matrix.platform.arch }}${{ matrix.platform.ext }} ./default.go
        env:
          GOOS: ${{ matrix.platform.os }}
          GOARCH: ${{ matrix.platform.arch }}
      - name: Upload release attachment
        uses: softprops/action-gh-release@v1
        with:
          files: default-${{ matrix.platform.os }}-${{ matrix.platform.arch }}${{ matrix.platform.ext }}